### ISSUE TITLE
Cylinder shape causes abnormal speeds while moving against a wall diagonally.

### ISSUE THREAD

**Issue by TheHyper-Dev** [DinkeyKing/Improved-KCC#1]
I loved your script but could you please make it compatible with a capsule collider as well? Thanks.

**Comment by DinkeyKing** [comment]
I'm sorry for keeping you waiting, but I'm currently reworking most of the script, so it will work better and more efficent. The current plan is to first get it to work with Godot Physics, at least with a box collider. Cylinder shapes are similiar to box shapes and I would prefer them, but they only work with Jolt. Capsule shapes are a bit different because of the resulting collision normals, I will see what I can do. Then I will test it with Jolt, but until most of the plugin's issues are solved, I wouldn't really bother with getting the script to work with it. Of course, after the new script is done, I will try to address and fix any issues that occour. So stay tuned, this will probably take a while.

**Comment by TheHyper-Dev** [comment]
Thank you, can't wait for your amazing work!

**Comment by DinkeyKing** [comment]
I've updated the project with the latest version of the new script (77b029e). The mentioned bug with the cylinder shape does not seem to be present, so I'll consider it fixed. As for the capsule shape, I opened a new issue to make stepping work with it #3. (The other features seem to be working well with a capsule shape.)
