### ISSUE TITLE
missing map.tscn

### ISSUE THREAD

**Issue by jasonswearingen** [DinkeyKing/Improved-KCC#2]
Hi I'm trying to run the demo scene but the map.tscn packed scene doesn't seem to be checked in.   How should I proceed?

I'm using Godot 4.3beta1.

**Comment by DinkeyKing** [comment]
Hi, looks like I made mistake. I forgot to create a map scene which is devoid of references to the Qodot addon, which I use for map creation (Qodot stuff is git ignored). I'm currently rewriting the script and also changing other stuff in the demo, because the currently uploaded implementation is pretty bad. Once I'm done, which shouldn't take too long now, I will pay attention to this when updating the project.

**Comment by jasonswearingen** [comment]
okay thank you.  I'm new to godot but may I suggest including the various addons in the repo?  to ensure the versions match/dependencies resolved.

**Comment by DinkeyKing** [comment]
The reason addons are not included, because they are only useful for me in aiding the development process (map making, debugging), they are not used by the character controller script, so I leave them out so that the demo project is smaller in size and complexity. While Godot Jolt is not necessary for the script to work, I highly recommend it, because character controllers greatly benefit from the improved collision detection of Jolt Physics. The only reason it's not included, is that it's really large in size.

**Comment by jasonswearingen** [comment]
thank you for the explanation, it makes sense.   I think I was able to get your demo scene working (I added some qodot packed scene as the map) so I will start off looking at what's here :)

Please feel free to close this, or leave it open for tracking purposes.

**Comment by DinkeyKing** [comment]
I've updated the project with the latest version of the script, and added the missing map scene (e9bc814).
